name: CI Build
on: pull_request

jobs:
  check-lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: NPM Install
        run: npm install
      - name: Check that package-lock.json has no changes
        run: exit $(git status --porcelain | wc -l)
  check-req-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: NPM Install
        run: npm install
      - name: Run req-gen
        run: npm run req-gen
      - name: Check that the requirements json has no changes
        run: exit $(git status --porcelain | wc -l) 
